apiVersion: v1
kind: ConfigMap
metadata:
  name: itsmsb-worker-configmap
  namespace: itsm-apps
data:
  BRANCH: feature-a                         # TODO: update it to actual main file path.
  PATH_TO_MAIN: services/payments/app.py    # TODO: update it to actual main file path.