apiVersion: apps/v1
kind: Deployment
metadata:
  name: itsmsb-worker
  namespace: itsm-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itsmsb-worker
  template:
    metadata:
      labels:
        app: itsmsb-worker
    spec:
      containers:
      - name: itsmsb-worker-container
        image: registry.example.com/itsmsb-worker-image:1.0.0   # TODO: Change to azure registry.
        
        envFrom:
          - configMapRef:
              name: itsmsb-worker-configmap

        volumeMounts:
          - name: itsmsb-code-repo
            mountPath: /itsmsb-code-repo
            
      volumes:
        - name: itsmsb-code-repo
          persistentVolumeClaim:
            claimName: itsmsb-code-repo
